Classification for IRIS Dataset

In [2]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 497.6/497.6 MB 506.5 kB/s eta 0:00:00m eta 0:00:010:00:23
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 587.8 kB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 KB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 KB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 593.0 kB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 589.0 kB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 585.0 kB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.5/14.5 MB 584.2 kB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 599.5 kB/s eta 0:00:001m639.7 kB/s eta 0:00:01
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.0/81.0 KB 2.6 MB/s eta 0:00:00
     ━━━━━━━━

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 KB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.5/151.5 KB 635.5 kB/s eta 0:00:002.5 MB/s eta 0:00:01
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4848 sha256=841422f33aa742f14f03d1fefec650d1d39fe1321a1151aca7d9fcc234d4fde4
  Stored in directory: /home/gck-16/.cache/pip/wheels/a0/16/9c/5473df82468f958445479c59e784896fa24f4a5fc024b0f501
Successfully built termcolor


In [9]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.datasets import load_iris

Dataset import

In [10]:
i = load_iris()
x = i.data
y = i.target

OneHot encoding

In [11]:
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [12]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


Train test with 20% Test split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(x, Y, test_size=0.2, random_state=0)

Model 
(Try with different units and activations)

In [14]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])

Optimizer and train
(Try different optimizers,Epochs,test splits)

In [15]:
opt = keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss='categorical_crossentropy', optimizer='rmsprop',metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=50, epochs=100)


Epoch 1/100
3/3 [==============================] - 0s 2ms/step - loss: 1.7072 - accuracy: 0.3667
Epoch 2/100
3/3 [==============================] - 0s 2ms/step - loss: 1.5592 - accuracy: 0.3667
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 1.4728 - accuracy: 0.3667
Epoch 4/100
3/3 [==============================] - 0s 2ms/step - loss: 1.4082 - accuracy: 0.3667
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 1.3605 - accuracy: 0.3750
Epoch 6/100
3/3 [==============================] - 0s 2ms/step - loss: 1.3198 - accuracy: 0.3750
Epoch 7/100
3/3 [==============================] - 0s 2ms/step - loss: 1.2799 - accuracy: 0.3750
Epoch 8/100
3/3 [==============================] - 0s 1ms/step - loss: 1.2451 - accuracy: 0.3500
Epoch 9/100
3/3 [==============================] - 0s 2ms/step - loss: 1.2106 - accuracy: 0.4000
Epoch 10/100
3/3 [==============================] - 0s 1ms/step - loss: 1.1842 - accuracy: 0.4083
Epoch 11/100
3/3 [===========

3/3 [==============================] - 0s 2ms/step - loss: 0.4850 - accuracy: 0.8750
Epoch 85/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4806 - accuracy: 0.8750
Epoch 86/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4774 - accuracy: 0.8500
Epoch 87/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4688 - accuracy: 0.8833
Epoch 88/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4642 - accuracy: 0.8667
Epoch 89/100
3/3 [==============================] - 0s 1ms/step - loss: 0.4557 - accuracy: 0.8833
Epoch 90/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4515 - accuracy: 0.9083
Epoch 91/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4460 - accuracy: 0.8750
Epoch 92/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4405 - accuracy: 0.9250
Epoch 93/100
3/3 [==============================] - 0s 1ms/step - loss: 0.4355 - accuracy: 0.8833
Epoch 94/100
3/3 [===============

Evaluation of Model

In [16]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.43984928727149963
Test accuracy: 0.8333333134651184


Testing 

In [17]:
y_pred = model.predict(X_test)
y_pred

array([[0.01012956, 0.16168049, 0.8281899 ],
       [0.10209503, 0.618207  , 0.27969798],
       [0.8732493 , 0.11910126, 0.00764942],
       [0.00474064, 0.2059206 , 0.7893387 ],
       [0.81491214, 0.17043427, 0.0146536 ],
       [0.00255403, 0.07386149, 0.92358446],
       [0.8377334 , 0.15092863, 0.01133792],
       [0.06639195, 0.52234304, 0.41126502],
       [0.05501919, 0.5588001 , 0.3861807 ],
       [0.12678476, 0.5903335 , 0.28288168],
       [0.00774875, 0.19690195, 0.7953493 ],
       [0.08026037, 0.49362877, 0.42611086],
       [0.04815648, 0.43942267, 0.5124209 ],
       [0.06215205, 0.5297822 , 0.4080658 ],
       [0.04611978, 0.4079445 , 0.5459358 ],
       [0.83721507, 0.14977966, 0.01300527],
       [0.05796182, 0.42813718, 0.51390105],
       [0.05115101, 0.39630383, 0.55254525],
       [0.7855735 , 0.19727202, 0.01715455],
       [0.86182183, 0.13014296, 0.00803531],
       [0.01586571, 0.1983632 , 0.78577113],
       [0.04638385, 0.326654  , 0.6269621 ],
       [0.

In [18]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Predicted: [2 1 0 2 0 2 0 1 1 1 2 1 2 1 2 0 2 2 0 0 2 2 0 0 2 0 0 1 1 0]
